# Page Settings
theme: jekyll-theme-minimal

title:  "Exploring Developmental Plasticity in Spadefoot Toads through Transcriptomics"
author: Clara Granado Beltrán
show_downloads: true
header:
  background_image: /assets/sapo_espuelas_Javier_Fuentes_Cuvier.jpg
navbar_links:
  - title: "Home"
    url: "/"
  - title: "Workflow"
    url: "/workflow"
  - title: "About"
    url: "/about"

# Footer settings
footer:
  links:
    - title: "Thesis GitHub Repository"
      url: "https://github.com/claragrabel/Masters_Thesis"
    - title: "Contact"
      url: "mailto:claragrabel@hotmail.com"
# Code syntax highlighting
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Enable syntax highlighting
highlight:
  theme: tomorrow

# Custom colors
color:
  primary: "#3c763d" # Green color
