# Page Settings
baseurl: ""
url: "https://github.com/claragrabel/Masters_Thesis"

# Theme settings
remote_theme: daattali/beautiful-jekyll

# Build settings
plugins:
  - jekyll-remote-theme

# Structure
title:  "Exploring Developmental Plasticity in Spadefoot Toads through Transcriptomics"
author: Clara Granado Beltrán
show_downloads: true

cover-img: "/assets/sapo_espuelas_Javier_Fuentes_Cuvier.jpg" 

navbar-links:
  Home Repository: "https://github.com/claragrabel/Masters_Thesis"

# Footer settings
footer:
  links:
    - title: "Thesis GitHub Repository"
      url: "https://github.com/claragrabel/Masters_Thesis"
    - title: "Contact"
      url: "mailto:claragrabel@hotmail.com"
    - title: "About me"
      url: "www.linkedin.com/in/claragrabel"
    - title: "About the group"
      url: "https://www.eco-evo-devo.com/"
      
# Code syntax highlighting
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Enable syntax highlighting
highlight:
  theme: tomorrow

# Color customization
page-col: "#388E3C"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#3c763d"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#3c763d"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

