theme: jekyll-theme-cayman

title:  "Exploring Developmental Plasticity in Spadefoot Toads through Transcriptomics"
description: "Welcome to my Master's Thesis project! In this website you will find the information and coding behind my Master's thesis on Developmental Plasticity in Spadefoot Toads from a Transcriptomics approach."
author: Clara Granado Beltrán
show_downloads: true
header:
  overlay_color: "#60a917"
  image: /assets/sapo_espuelas_Javier_Fuentes_Cuvier.jpg
navbar_links:
  - title: "Home"
    url: "/"
  - title: "Workflow"
    url: "/workflow"
  - title: "Results"
    url: "/results"
  - title: "About"
    url: "/about"
# Footer settings
footer:
  links:
    - title: "GitHub Repository"
      url: [(https://github.com/claragrabel/Masters_Thesis]
    - title: "Contact"
      url: "mailto:[claragrabel@hotmail.com]"
