---
# Page Settings
url: "https://github.com/claragrabel/Masters_Thesis"

# Theme settings
remote_theme: daattali/beautiful-jekyll@6.0.1

# Structure
title:  "Exploring Developmental Plasticity in Spadefoot Toads through Transcriptomics"
author: Clara Granado Beltrán
avatar: "/assets/sapo_espuelas_Javier_Fuentes_Cuvier.jpg"
round-avatar: true
page-img: "/assets/pelobates_white_bg.jpg"

navbar-links:
  Home Repository: "https://github.com/claragrabel/Masters_Thesis"

# Footer settings
social-network-links:
  email: "claragrabel@hotmail.com"
  linkedin: "www.linkedin.com/in/claragrabel"

# Code syntax highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Color customization
page-col: "#FFFFFF" # Keeping the page background white for readability
text-col: "#404040" # Dark Slate Gray for text, which is easier to read and has a natural tone
link-col: "#006400" # Dark Green for links to match the toad theme
hover-col: "#228B22" # Forest Green for hover effects on links for better visibility
navbar-col: "#E0EEE0" # Light Green background for the navbar
navbar-text-col: "#2F4F4F" # Dark Slate Gray for navbar text
navbar-border-col: "#8FBC8F" # Dark Sea Green for navbar borders to blend subtly
footer-col: "#E0EEE0" # Light Green background for the footer
footer-text-col: "#556B2F" # Dark Olive Green for footer text to differentiate from main text
footer-link-col: "#006400" # Dark Green for footer links
footer-hover-col: "#228B22" # Forest Green for hover effects on footer links
---
