---
title: "POC_Visualization"
author: "clagrabel"
date: "2024-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
pacman::p_load(tidyverse, DESeq2, ggVennDiagram, UpSetR, plotly, ggrepel, scico)
```


```{r}
degs_pop_by_pop<-lapply(list(Jab_group, Lla_group, Esp_group, Bui_group, Tur_group, Can_group), FUN=extract_degs)
names(degs_pop_by_pop) <-c("Jab_group", "Lla_group", "Esp_group", "Bui_group", "Tur_group", "Can_group")
list_degs_pop_by_pop<-degs_pop_by_pop[c("Jab_group", "Lla_group", "Esp_group", "Bui_group", "Tur_group", "Can_group")]
```

```{r}
upset(fromList(list_degs_pop_by_pop),
      number.angles = 0, point.size = 3, line.size = 1,
      sets.x.label = "Number of DEGs",
      set_size.show = TRUE,
      sets=c("Jab_group", "Lla_group", "Esp_group", "Bui_group", "Tur_group", "Can_group"),
      set_size.scale_max = max(sapply(list_degs_pop_by_pop, length))+100, 
      # text.scale = c(1.2, 1.2, 1.2, 1.2, 1.5, 1.5),
      order.by=c("degree","freq"))
```


```{r}
Cs(poc_EspH_EspL,poc_JabH_JabL,poc_LlaH_LlaL)

degs_south<-lapply(list(poc_EspH_EspL, poc_JabH_JabL, poc_LlaH_LlaL), FUN=extract_degs)
names(degs_south) <-Cs(poc_EspH_EspL,poc_JabH_JabL,poc_LlaH_LlaL)
list_degs_south<-degs_south[Cs(poc_EspH_EspL,poc_JabH_JabL,poc_LlaH_LlaL)]
```

```{r}
upset(fromList(degs_south),
      number.angles = 0, point.size = 3, line.size = 1,
      sets.x.label = "Number of DEGs",
      set_size.show = TRUE,
      sets=Cs(poc_EspH_EspL,poc_JabH_JabL,poc_LlaH_LlaL),
      set_size.scale_max = max(sapply(degs_south, length))+100, 
      # text.scale = c(1.2, 1.2, 1.2, 1.2, 1.5, 1.5),
      order.by=c("degree","freq"))
```

```{r}
library(Hmisc)

Cs(poc_BuiH_BuiL,poc_CanH_CanL,poc_TurH_TurL)

degs_central<-lapply(list(poc_BuiH_BuiL,poc_CanH_CanL,poc_TurH_TurL), FUN=extract_degs)
names(degs_central) <-Cs(poc_BuiH_BuiL,poc_CanH_CanL,poc_TurH_TurL)

upset(fromList(degs_central),
      number.angles = 0, point.size = 3, line.size = 1,
      sets.x.label = "Number of DEGs",
      set_size.show = TRUE,
      sets=Cs(poc_BuiH_BuiL,poc_CanH_CanL,poc_TurH_TurL),
      set_size.scale_max = max(sapply(degs_central, length)+2), 
      # text.scale = c(1.2, 1.2, 1.2, 1.2, 1.5, 1.5),
      order.by=c("degree","freq"))
```

```{r}
Cs(poc_pop_only_Esp_Lla,poc_pop_only_Jab_Lla,poc_pop_only_Jab_Esp)

degs_between_south<-lapply(list(poc_pop_only_Esp_Lla,poc_pop_only_Jab_Lla,poc_pop_only_Jab_Esp), FUN=extract_degs)
names(degs_between_south) <-Cs(poc_pop_only_Esp_Lla,poc_pop_only_Jab_Lla,poc_pop_only_Jab_Esp)

upset(fromList(degs_between_south),
      number.angles = 0, point.size = 3, line.size = 1,
      sets.x.label = "Number of DEGs",
      set_size.show = TRUE,
      sets=Cs(poc_pop_only_Esp_Lla,poc_pop_only_Jab_Lla,poc_pop_only_Jab_Esp),
      set_size.scale_max = max(sapply(degs_between_south, length)+10), 
      # text.scale = c(1.2, 1.2, 1.2, 1.2, 1.5, 1.5),
      order.by=c("degree","freq"))
```






```{r}
Cs(poc_pop_only_Bui_Can,poc_pop_only_Bui_Tur,poc_pop_only_Can_Tur)

degs_between_central<-lapply(list(poc_pop_only_Bui_Can,poc_pop_only_Bui_Tur,poc_pop_only_Can_Tur), FUN=extract_degs)
names(degs_between_central) <-Cs(poc_pop_only_Bui_Can,poc_pop_only_Bui_Tur,poc_pop_only_Can_Tur)

upset(fromList(degs_between_central),
      number.angles = 0, point.size = 3, line.size = 1,
      sets.x.label = "Number of DEGs",
      set_size.show = TRUE,
      sets=Cs(poc_pop_only_Bui_Can,poc_pop_only_Bui_Tur,poc_pop_only_Can_Tur),
      set_size.scale_max = max(sapply(degs_between_central, length)+100), 
      # text.scale = c(1.2, 1.2, 1.2, 1.2, 1.5, 1.5),
      order.by=c("degree","freq"))
```